services:
        web:
          build:
              context: .
              dockerfile: dockerfile
          container_name: mydocker
          ports:
              - "8000:8000"
          volumes:
              - .:/app
          environment:
              - UVICORN_RELOAD=1
          depends_on:
              - db
        db:
          image: postgres:15
          container_name: mydocker-db
          ports:
              - "5432:5432"
          env_file:
              - .env
          volumes:
              - ./db_data:/var/lib/postgresql/data
          restart: always

